# Generated by Django 4.2.7 on 2023-11-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default='temporal_password', max_length=255),
        ),
    ]
